### ISSUE TITLE
Error while setting up platform tuya

### ISSUE THREAD

**Issue by mario-g0** [sean6541/tuya-homeassistant#18]
I followed the whole procedure of copying tuya.py in custom_components/switch, figured out all the id needed, but when I restarted hassio I got the following error:

Error while setting up platform tuya
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/tuya.py", line 39, in setup_platform
    import pytuya
ModuleNotFoundError: No module named 'pytuya'

but if I check in \deps\lib\python3.6\site-packages\pytuya I can see the pytuya module

what's going on?

**Comment by Thunderbird2086** [comment]
Dependent package should be installed same parent directory as `homeassistant` module. 
In your case, it should be `/usr/lib/python3.6/site-packages/'.
Did you activate virtual environment [something like](https://www.home-assistant.io/docs/installation/virtualenv/)?:
```
$ source bin/activate
```

**Comment by mario-g0** [comment]
it was easier than that, I just had to force close the phone app... apparently the component will not work if the device is working with another service/app
