### ISSUE TITLE
 get access token failed

### ISSUE THREAD

**Issue by pickeld** [sean6541/tuya-homeassistant#19]
hey guys
few minutes ago i've reset hass server and got this error. and the Tuya Smart App everything working as expected.
is anyone else getting this?
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/tuya.py", line 63, in setup
    tuya.init(username, password, country_code)
  File "/usr/local/lib/python3.6/site-packages/tuyapy/tuyaapi.py", line 44, in init
    self.get_access_token()
  File "/usr/local/lib/python3.6/site-packages/tuyapy/tuyaapi.py", line 62, in get_access_token
    raise TuyaAPIException("get access token failed")
tuyapy.tuyaapi.TuyaAPIException: get access token failed
```

**Comment by pickeld** [comment]
@manuel-jrs thank you, 
should i just add the platform tag or should i update more files?
i've tried adding the platform as follow:

```
tuya: 
  username: xx@xx.com
  password: xx
  country_code: xx
  platform: 'tuya'
```
but configuration validation return an error.

**Comment by manuel-jrs** [comment]
Just add the platform tag.

Did you check your username and password?
