### ISSUE TITLE
Syntax error on <!DOCTYPE html> Line 7????

### ISSUE THREAD

**Issue by SDeGonge** [sean6541/tuya-homeassistant#3]
Not sure if just something I did but I get a syntax error when tuya.py loads...

2018-01-28 10:53:25 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=41 from 2018-01-28 15:48:45.558803)
2018-01-28 10:53:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 60, in async_setup_component
    return (yield from task)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 159, in _async_setup_component
    conf_util.async_process_component_config(hass, config, domain)
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 624, in async_process_component_config
    platform = get_platform(domain, p_name)
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 104, in get_platform
    return get_component(PLATFORM_FORMAT.format(domain, platform))
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  **File "/config/custom_components/switch/tuya.py", line 7
    '<'!DOCTYPE html'>'
    ^
SyntaxError: invalid syntax**
2018-01-28 10:53:48 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-01-28 10:54:02 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.

**Comment by SDeGonge** [comment]
Problem solved:  I had downloaded the tuya.py file which seemed to format it as an HTML document.  Instead, I copy/pasted the code into and that solved that problem.  Still getting an error but now it's different.  Will post another thread.
